# A3

https://bugzilla.mozilla.org/show_bug.cgi?id=1532316

## Diagnosis of Bug

The bug I chose is one where not enough information is present when a raptor test is ran. If one tries to run 
"./mach raptor-test --test <test-name>" on a test that does not exist or has been disabled then an error is reported in the following format:
15:23:45 INFO - raptor-manifest abort: specified test name doesn't exist

15:23:45 INFO - raptor-main abort: no tests found


The second error needs to include the test name so the "no tests found" error message is more meaningful.

## Solution

My solution is to pass the name of the test to the error message so that the error message says "no tests found for the given test: <testname>"
Step by step process:
1. Look at the main function in raptor.py to see that it returns that error by calling get_raptor_test_list in manifest.py
2. Observe code in the function get_raptor_test_list in /testing/raptopr/raptor/manifest.py 
2. Update error message to have test name
3. Run "./mach raptor-test --test <test-name>" to see if the correct error message is returned

## Check if fix worked

Process: I will carry out the steps in the solution detailed above and run "./mach raptor-test --test thing". I know that 'thing' isn't 
an existing test so it should return "no tests found" before the fix and my custom error message after the fix.

Fix before bug fix
https://drive.google.com/file/d/1dYbCZ4U4wJQ9feMCm_SttzQQopbZQMZm/view?usp=sharing

Fix after bug fix
https://drive.google.com/file/d/1GjpRO_d0McIo1DfNHunrLIxHXAqOn5mV/view?usp=sharing
